### ISSUE TITLE
Update versioning section

### ISSUE THREAD

**Issue by vlymar** [dobtco/screendoor-api-docs#21]
http://dobtco.github.io/screendoor-api-docs/#versioning says:

```
The current API version is 0.

Specify the API version by setting a Version: 0 HTTP header
Alternatively, use the ?v=0 URL parameter
```

Current API version actually is 1.1.2, so that's bad advice.

We should probably direct people to get the API version from screendoor itself, so we don't have to update it here constantly (or grab the most recent version # from rails-assets or cloudfront somehow).

My second concern is that the API documentation is for version 0 itself, and does not reflect version 1 changes.

- [ ] remove hardcoded version 0
- [ ] make sure api docs are appropriate for version 1

**Comment by kariannemah** [comment]
>We should probably direct people to get the API version from screendoor itself

I'm confused: Where do we show the current API version in UI?

**Comment by kariannemah** [comment]
We do show the current version of _formrenderer-base_ in Screendoor's UI under the embed code:

![](http://dobt-misc.s3.amazonaws.com/Screen-Shot-2017-10-02-at-3.08.43-PM.png)

That "documentation" link goes to https://github.com/dobtco/formrenderer-base not http://dobtco.github.io/screendoor-api-docs/.

Screendoor's API versioning is distinct from this isn't it? AFAIK, it's still at v0.

**Comment by vlymar** [comment]
I totally mixed up formrenderer versioning and api versioning. API versioning is actually fine.
