### ISSUE TITLE
Docs for response fields schema

### ISSUE THREAD

**Issue by ajb** [dobtco/screendoor-api-docs#7]

**Comment by ajb** [comment]
Once everything's converted over to Slate, it would be really great to add some information on the schema of our response fields -- basically, how to format a hash so that Screendoor can properly convert it into a `Response`.

Here's an example ripped from our formrenderer-base test suite:

```json
{
  "35": "foo",
  "36": "bar",
  "37": {
    "0": "on",
    "1": false
  },
  "39": "Choice #2",
  "40": "Choice #2",
  "41": {
    "dollars": "12",
    "cents": "99"
  },
  "42": "123",
  "43": {
    "month": "12",
    "day": "30",
    "year": "2014"
  },
  "44": {
    "am_pm": "PM",
    "hours": "6",
    "minutes": "01",
    "seconds": "30"
  },
  "45": "http://www.google.com",
  "46": "",
  "47": "foo@bar.com",
  "48": {
    "country": "GB",
    "street": "123 main st",
    "state": null
  },
  "49": {
    "0": ["hey", ""],
    "1": ["", "nay"]
  },
  "50": {
    "lat": "40.7700118",
    "lng": "-73.9800453"
  }
}
```

You should be able to start with the field types in there, and I can fill you in on other bits. Maybe ping me when you're ready to start and I'll walk you through it :+1:

**Comment by ajb** [comment]
Maybe this week?

**Comment by kariannemah** [comment]
Yes. It's on my list.
